export interface Player {
  id: string;
  name: string;
  shortName: string;
  country: string;
  flag: string;
  jersey: string;
  era: "Active" | "Legend";
  gradientFrom: string;
  gradientTo: string;
  imagePath: string;
  totalWins: number;
  totalAppearances: number;
  winRate: number;
}

export const ACTIVE_PLAYERS: Player[] = [
  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    shortName: "Ronaldo",
    country: "Portugal",
    flag: "🇵🇹",
    jersey: "CR7",
    era: "Active",
    gradientFrom: "#006400",
    gradientTo: "#009900",
    imagePath: "/ronaldo-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "messi",
    name: "Lionel Messi",
    shortName: "Messi",
    country: "Argentina",
    flag: "🇦🇷",
    jersey: "#10",
    era: "Active",
    gradientFrom: "#74ACDF",
    gradientTo: "#4A90D9",
    imagePath: "/messi-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "mbappe",
    name: "Kylian Mbappé",
    shortName: "Mbappé",
    country: "France",
    flag: "🇫🇷",
    jersey: "#7",
    era: "Active",
    gradientFrom: "#002395",
    gradientTo: "#ED2939",
    imagePath: "/mbappe-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "haaland",
    name: "Erling Haaland",
    shortName: "Haaland",
    country: "Norway",
    flag: "🇳🇴",
    jersey: "#9",
    era: "Active",
    gradientFrom: "#EF2B2D",
    gradientTo: "#003087",
    imagePath: "/haaland-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "vinicius",
    name: "Vinícius Jr.",
    shortName: "Vinícius Jr.",
    country: "Brazil",
    flag: "🇧🇷",
    jersey: "#7",
    era: "Active",
    gradientFrom: "#009C3B",
    gradientTo: "#FFDF00",
    imagePath: "/vinicius-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "bellingham",
    name: "Jude Bellingham",
    shortName: "Bellingham",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    jersey: "#22",
    era: "Active",
    gradientFrom: "#C8102E",
    gradientTo: "#1C3160",
    imagePath: "/bellingham-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "pedri",
    name: "Pedri",
    shortName: "Pedri",
    country: "Spain",
    flag: "🇪🇸",
    jersey: "#8",
    era: "Active",
    gradientFrom: "#AA151B",
    gradientTo: "#F1BF00",
    imagePath: "/pedri-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "rodri",
    name: "Rodri",
    shortName: "Rodri",
    country: "Spain",
    flag: "🇪🇸",
    jersey: "#16",
    era: "Active",
    gradientFrom: "#AA151B",
    gradientTo: "#F1BF00",
    imagePath: "/rodri-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "kane",
    name: "Harry Kane",
    shortName: "Kane",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    jersey: "#9",
    era: "Active",
    gradientFrom: "#C8102E",
    gradientTo: "#1C3160",
    imagePath: "/kane-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "yamal",
    name: "Lamine Yamal",
    shortName: "L. Yamal",
    country: "Spain",
    flag: "🇪🇸",
    jersey: "#19",
    era: "Active",
    gradientFrom: "#AA151B",
    gradientTo: "#F1BF00",
    imagePath: "/yamal-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
];

export const LEGEND_PLAYERS: Player[] = [
  {
    id: "pele",
    name: "Pelé",
    shortName: "Pelé",
    country: "Brazil",
    flag: "🇧🇷",
    jersey: "#10",
    era: "Legend",
    gradientFrom: "#009C3B",
    gradientTo: "#FFDF00",
    imagePath: "/pele-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "maradona",
    name: "Diego Maradona",
    shortName: "Maradona",
    country: "Argentina",
    flag: "🇦🇷",
    jersey: "#10",
    era: "Legend",
    gradientFrom: "#74ACDF",
    gradientTo: "#4A90D9",
    imagePath: "/maradona-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "zidane",
    name: "Zinedine Zidane",
    shortName: "Zidane",
    country: "France",
    flag: "🇫🇷",
    jersey: "#10",
    era: "Legend",
    gradientFrom: "#002395",
    gradientTo: "#ED2939",
    imagePath: "/zidane-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "ronaldinho",
    name: "Ronaldinho",
    shortName: "Ronaldinho",
    country: "Brazil",
    flag: "🇧🇷",
    jersey: "#10",
    era: "Legend",
    gradientFrom: "#009C3B",
    gradientTo: "#FFDF00",
    imagePath: "/ronaldinho-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "r9",
    name: "Ronaldo Nazário",
    shortName: "R9",
    country: "Brazil",
    flag: "🇧🇷",
    jersey: "#9",
    era: "Legend",
    gradientFrom: "#009C3B",
    gradientTo: "#FFDF00",
    imagePath: "/ronaldo-nazario-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "cruyff",
    name: "Johan Cruyff",
    shortName: "Cruyff",
    country: "Netherlands",
    flag: "🇳🇱",
    jersey: "#14",
    era: "Legend",
    gradientFrom: "#FF6600",
    gradientTo: "#CC4400",
    imagePath: "/cruyff-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "beckenbauer",
    name: "Franz Beckenbauer",
    shortName: "Beckenbauer",
    country: "Germany",
    flag: "🇩🇪",
    jersey: "#5",
    era: "Legend",
    gradientFrom: "#2C2C2C",
    gradientTo: "#DD0000",
    imagePath: "/beckenbauer-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "henry",
    name: "Thierry Henry",
    shortName: "T. Henry",
    country: "France",
    flag: "🇫🇷",
    jersey: "#12",
    era: "Legend",
    gradientFrom: "#002395",
    gradientTo: "#ED2939",
    imagePath: "/henry-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "rcarloss",
    name: "Roberto Carlos",
    shortName: "R. Carlos",
    country: "Brazil",
    flag: "🇧🇷",
    jersey: "#6",
    era: "Legend",
    gradientFrom: "#009C3B",
    gradientTo: "#FFDF00",
    imagePath: "/roberto-carlos-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
  {
    id: "iniesta",
    name: "Andrés Iniesta",
    shortName: "Iniesta",
    country: "Spain",
    flag: "🇪🇸",
    jersey: "#8",
    era: "Legend",
    gradientFrom: "#AA151B",
    gradientTo: "#F1BF00",
    imagePath: "/iniesta-card.png",
    totalWins: 0,
    totalAppearances: 0,
    winRate: 0,
  },
];

// All 20 players combined — active first, legends second
export const PLAYERS: Player[] = [...ACTIVE_PLAYERS, ...LEGEND_PLAYERS];

// Homepage squad — legends left, active right
export const HOME_LEFT: Player[] = [
  LEGEND_PLAYERS.find((p) => p.id === "pele")!,
  LEGEND_PLAYERS.find((p) => p.id === "maradona")!,
  LEGEND_PLAYERS.find((p) => p.id === "zidane")!,
  LEGEND_PLAYERS.find((p) => p.id === "ronaldinho")!,
  LEGEND_PLAYERS.find((p) => p.id === "r9")!,
];

export const HOME_RIGHT: Player[] = [
  ACTIVE_PLAYERS.find((p) => p.id === "ronaldo")!,
  ACTIVE_PLAYERS.find((p) => p.id === "messi")!,
  ACTIVE_PLAYERS.find((p) => p.id === "mbappe")!,
  ACTIVE_PLAYERS.find((p) => p.id === "haaland")!,
  ACTIVE_PLAYERS.find((p) => p.id === "bellingham")!,
];
